#!/bin/bash

if [ -z $1 ];
then
  echo "No keyword"
  exit
fi

response=$(curl -s https://source.unsplash.com/1600x900/?$1)
bg=$( echo $response | grep -Po "http(s)?://.(?:(?!\").)*" )

gsettings set org.gnome.desktop.background picture-uri $bg
